/* Catálogo da XT Brazil. Edite preço, estoque, descrição e imagem aqui. */
const PRODUCTS = [
  { id: 1, name: "Sensi VIP", category: "sensi", price: 25.00, stock: 100, badge: "PERSONALIZÁVEL", image: "assets/celulares.svg", description: "Configuração de sensibilidade personalizada para o modelo do seu celular." },
  { id: 3, name: "Conjunto Naruto", category: "codiguin", price: 130.00, stock: 0, badge: "CODIGUIN", image: "https://www.freefiremania.com.br/images/itens/Icon_bundle_male_NB_Yellow_47.png", description: "Codiguin do Conjunto Naruto. Consulte a disponibilidade antes da confirmação." },
  { id: 4, name: "Conjunto Coelho Elétrico", category: "codiguin", price: 100.00, stock: 0, badge: "CODIGUIN", image: "https://www.freefiremania.com.br/images/itens/Icon_bundle_male_Easterrabbit_Purple_40.png", description: "Codiguin do Conjunto Coelho Elétrico. Consulte a disponibilidade antes da confirmação." },
  { id: 5, name: "Conjunto Catiorão de Ouro", category: "codiguin", price: 110.00, stock: 0, badge: "CODIGUIN", image: "https://www.freefiremania.com.br/images/itens/Icon_bundle_male_Catdog_48.png", description: "Codiguin do Conjunto Catiorão de Ouro. Consulte a disponibilidade antes da confirmação." },
  { id: 6, name: "Lua Sangrenta (Samurai Sangrento)", category: "codiguin", price: 100.00, stock: 0, badge: "CODIGUIN", image: "https://www.freefiremania.com.br/images/itens/Icon_female_bloodmoon.png", description: "Codiguin Lua Sangrenta (Samurai Sangrento). Consulte a disponibilidade antes da confirmação." },
  { id: 7, name: "Conjunto Cobra: Modo Fúria", category: "prime", price: 225.00, contactOnly: true, stock: 1, badge: "LOJA PRIME", image: "https://www.freefiremania.com.br/images/itens/Icon_bundle_male_Cobra_Red_26.png", description: "Item atual da Loja Prime de Free Fire. Consulte a disponibilidade pelo atendimento." },
  { id: 11, name: "Conjunto Círculo de Cupuaçu", category: "prime", price: 60.00, contactOnly: true, stock: 1, badge: "LOJA PRIME", image: "https://www.freefiremania.com.br/images/combinacao/2022-10-09-01-21-53-como-nunca-visto-antes-100-circulo-de-cupuacu-incubadora.jpg", description: "Item atual da Loja Prime de Free Fire. Consulte a disponibilidade pelo atendimento." },
  { id: 12, name: "Conjunto Geometria de Morango", category: "prime", price: 60.00, contactOnly: true, stock: 1, badge: "LOJA PRIME", image: "https://www.freefiremania.com.br/images/itens/Icon_bundle_male_Silversword_Red_31.png", description: "Item atual da Loja Prime de Free Fire. Consulte a disponibilidade pelo atendimento." },
  { id: 13, name: "Punho - Cobra", category: "prime", price: 180.00, contactOnly: true, stock: 1, badge: "LOJA PRIME", image: "https://www.freefiremania.com.br/images/itens/Icon_FIST_Cobra.png", description: "Item especial atual da Loja Prime de Free Fire. Consulte a disponibilidade pelo atendimento." },
  { id: 14, name: "Groza - Moderninha", category: "prime", price: 90.00, contactOnly: true, stock: 1, badge: "LOJA PRIME", image: "https://www.freefiremania.com.br/images/itens/Icon_Groza_Sayori_03.png", description: "Skin de arma atual da Loja Prime de Free Fire. Consulte a disponibilidade pelo atendimento." },
  { id: 15, name: "M1887 - Agentes Dourados", category: "prime", price: 90.00, contactOnly: true, stock: 1, badge: "LOJA PRIME", image: "https://www.freefiremania.com.br/images/itens/Icon_M1887_Digitaluniverse03.png", description: "Skin de arma atual da Loja Prime de Free Fire. Consulte a disponibilidade pelo atendimento." },
  { id: 8, name: "Contas Free Fire disponíveis", category: "conta", price: 50.00, priceLabel: "R$ 50,00 a R$ 500,00", contactOnly: true, stock: 1, badge: "CONTAS", image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=900&q=85", description: "O preço varia conforme os itens e o inventário da conta disponível. Consulte o catálogo atualizado pelo atendimento." },
  { id: 9, name: "Acompanhamento Completo", category: "kit", price: 120.90, stock: 20, badge: "ACOMPANHAMENTO", image: "https://chuky.vn/wp-content/uploads/2025/12/Ma-setting-3-ngon-Free-Fire.webp", description: "Acompanhamento completo para ajustar sensibilidade, mira e HUD de acordo com seu aparelho e estilo de jogo." },
  { id: 10, name: "Métodos de Mira 2x e 4x", category: "kit", price: 39.90, stock: 10, badge: "MIRA 2X", image: "https://www.saudigamer.com/tachyon/sites/6/2024/12/image-42-1.png", description: "Métodos de mira com foco na UMP e na mira 2x para treinar puxadas e buscar capa com mais consistência." }
];
